spring:
  application:
    name: ironlog-boot
  config:
    import:
      - 'classpath:credentials.yaml'
      - 'optional:classpath:./permissions/'
  profiles:
    default: pdn
server:
  port: ${PORT}
  servlet:
    context-path: /api/v1